### ISSUE TITLE
Access to dataset fails

### ISSUE THREAD

**Issue by armandal88** [akshaygopalkr/EM-VLM4AD#1]
Hi,
Thanks for this contribution!
It seems that the dataset is no longer available. Can you check the link ?
thanks in advance
Alex

**Comment by akshaygopalkr** [comment]
Hello! Sorry for the delay, the dataset link has been updated on the Github: https://drive.google.com/file/d/1isiXXTg46nl5SqMiEV4XjFD71KCCzezi/view?usp=sharing. Let me know if it is working for you now.

**Comment by armandal88** [comment]
> Hello! Sorry for the delay, the dataset link has been updated on the Github: https://drive.google.com/file/d/1isiXXTg46nl5SqMiEV4XjFD71KCCzezi/view?usp=sharing. Let me know if it is working for you now.

Hi, thanks a lot it works now :)
Best
